apiVersion: v1
kind: Service
metadata:
  name: load-agent-service
  namespace: snet

spec:
  type: NodePort
  ports:
  - name: load-agent
    port: 9090
    targetPort: 9090
    nodePort: 30003
  - name: load-agent-2
    port: 9091
    targetPort: 9091
    nodePort: 30005
