apiVersion: v1
kind: Service
metadata:
  name: load-agent-service
  namespace: snet

spec:
  type: NodePort
  ports:
  - name: load-agent
    port: 9090
    targetPort: load-agent
    nodePort: 30003
