apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: silly-net
build:
  artifacts:
    - image: db-migration
      context: services/db
    - image: front-p
      context: services/python/front
manifests:
  rawYaml:
    - infra/manifests/app-conf.yaml
    - infra/manifests/db.yaml
    - infra/manifests/front.p.yaml
    - infra/manifests/db-migrate.yaml
portForward:
  - resourceType: service
    resourceName: db-service
    namespace: snet
    port: 5432
  - resourceType: service
    resourceName: front-service
    namespace: snet
    port: 8080
