apiVersion: v1
kind: Namespace
metadata:
  name: snet
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: snet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: snet
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-data
        - name: config
          configMap:
            name: pghbaconf
            items:
              - key: "pg_hba.conf"
                path: "pg_hba.conf"
      containers:
      - name: postgres
        image: postgres:16-alpine
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
          - name: config
            readOnly: false
            mountPath: "/etc/pg_hba.conf"
            subPath: "pg_hba.conf"
        args: ['-c', 'hba_file=/etc/pg_hba.conf']
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 2000m
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: snet
        ports:
        - name: postgres
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: pg-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        ports:
          - name: pg-exporter
            containerPort: 9187
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /readiness
            port: 9187
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /liveness
            port: 9187
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
          - name: DATA_SOURCE_NAME
            value: "postgresql://postgres:postgres@localhost:5432/snet?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: snet
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  - name: pg-exporter
    port: 9187
    targetPort: pg-exporter  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pghbaconf
  namespace: snet
data:
  # file-like keys
  pg_hba.conf: |
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             0.0.0.0/0               trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             0.0.0.0/0               trust
    host    replication     all             ::1/128                 trust
