apiVersion: v1
kind: Namespace
metadata:
  name: snet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-datasources
  namespace: snet
data:
  sources.yaml: |
    apiVersion: 1
    
    deleteDatasources:
      - name: Tempo
        orgId: 1
    
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo.snet.svc.cluster.local:3200
        access: proxy
        isDefault: true
        jsonData:
          tracesToMetrics:
          datasourceUid: 'Prometheus'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
          serviceMap:
            datasourceUid: 'Prometheus'
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus.snet.svc.cluster.local:9090
        access: proxy
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 2.44.0
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.snet.svc.cluster.local:3101
        jsonData:
          maxLines: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-dashboards
  namespace: snet
data:
  dashboards.yaml: |
    apiVersion: 1
    
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /etc/dashboards
          foldersFromFilesStructure: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: snet
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      namespace: snet
      labels:
        app: grafana
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: grafana
          image: grafana/grafana:10.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: 'false'
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: 'false'
            - name: GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES
              value: 'false'
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: 'traceqlEditor'
            - name: GF_SERVER_HTTP_PORT
              value: '3100'
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: 'Admin'
          ports:
            - containerPort: 3100
              name: http-grafana
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: http-grafana
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http-grafana
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 3750m
          volumeMounts:
            - name: config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: config-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /etc/dashboards
      volumes:
        - name: config-datasources
          configMap:
            name: grafana-conf-datasources
        - name: config-dashboards
          configMap:
            name: grafana-conf-dashboards
        - name: dashboards
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: snet
spec:
  selector:
    app: grafana
  ports:
    - name: http-grafana
      port: 3100
      targetPort: http-grafana
