# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-01-28T19:34:24+00:00

from __future__ import annotations

from typing import List, Optional

from .models import AuthLoginPostRequest, AuthLoginPostResponse, ListUsersRequest, User


def user_login(body: AuthLoginPostRequest = None) -> AuthLoginPostResponse:
    pass


def user_sign_up(body: User = None) -> User:
    pass


def list_users(filters: Optional[ListUsersRequest] = None) -> List[User]:
    pass


def get_user(id: str) -> User:
    pass
