apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./db-migrate.yaml
  - ../config/
images:
  - name: migrate-image
    newName: vladnf/snet/snet-api-migrate
    newTag: 0.0.1
