kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # SNet-API
  - containerPort: 8080
    hostPort: 8080
  # SNet-API debug
  - containerPort: 8081
    hostPort: 8081
  # Metrics
  - containerPort: 3001
    hostPort: 3001
  # Metrics debug
  - containerPort: 4001
    hostPort: 4001
  # Grafana
  - containerPort: 3100
    hostPort: 3100
  # Postgres
  - containerPort: 5432
    hostPort: 5432
  # Prometheus
  - containerPort: 9090
    hostPort: 9090
  # Tempo (tracing)
  - containerPort: 9411
    hostPort: 9411
