kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # SNet-API
  - containerPort: 30001
    hostPort: 8080
  # Postgres
  - containerPort: 30002
    hostPort: 5432
  # Load Agent
  - containerPort: 30003
    hostPort: 9090
  # Grafana
  - containerPort: 30004
    hostPort: 3100
