apiVersion: v1
kind: Namespace
metadata:
  name: snet
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-rollback-job
  namespace: snet
spec:
  template:
    metadata:
      labels:
        app: db-rollback-job
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-data-migration
          image: busybox
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
                  optional: true
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_port
                  optional: true
          command:
            [
              "sh",
              "-c",
              "until nc -w 2 $(POSTGRES_HOST) $(POSTGRES_PORT); do echo Waiting for postgres; sleep 2; done;",
            ]
      containers:
        - name: db-migration
          image: db-migration
          command: ["sh", "rollback.sh"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_user
                  optional: true
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_password
                  optional: true
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_name
                  optional: true
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
                  optional: true
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_port
                  optional: true
            - name: ROLLBACK_REVISION
              value: 20230304_01_search_index
