apiVersion: v1
kind: Service
metadata:
  name: services-db
  labels:
    app: services-db
spec:
  ports:
  - port: 5432
    protocol: TCP
  clusterIP: None
  selector:
    app: services-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-db
  labels:
    app: services-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services-db
  template:
    metadata:
      labels:
        app: services-db
    spec:
      containers:
      - name: services-db
        image: services-db
