{
 "title": "SNet Basics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(snet_front_requests_total[1m])",
     "legendFormat": "REQ {{method}}:{{endpoint}}"
    },
    {
     "expr": "rate(snet_front_requests_failed_total[1m])",
     "legendFormat": "FAILED {{method}}:{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(snet_front_request_time_sum[1m])/rate(snet_front_request_time_count[5m])",
     "legendFormat": "AVG {{method}} -- {{dsn}}"
    }
   ]
  },
  {
   "title": "DB Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(snet_db_requests_total[1m])",
     "legendFormat": "REQ {{method}}:{{dsn}}"
    }
   ]
  },
  {
   "title": "DB Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(snet_db_request_time_sum[1m])/rate(snet_db_request_time_count[5m])",
     "legendFormat": "AVG {{method}} -- {{dsn}}"
    }
   ]
  }
 ]
}