version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: snet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d snet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    volumes:
      - ./app:/snet/app
    ports:
      - "8000:8000"
    command: uvicorn app.views.main:app --reload --host 0.0.0.0
volumes:
  pgdata:
